[manager]

show_hidden = true  # show hidden files
ratio = [1, 2, 5]  # Ratio to display the sections in the screen, by eighths, e.g. 1 = 1/8 of screen 

# what to display in line
linemode = "size"

# sorting
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true

[preview]
max_width = 2000
max_height = 2000

[opener]
# File opening rules
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open", for = "unix" },
]

[plugin]
prepend_previewers = [
	{ mime = "text/csv", exec = "miller", run = "miller" }
]
